### ISSUE TITLE
希望提供API关闭地区选择

### ISSUE THREAD

**Issue by ghost** [WangLiquan/EWAddressPicker-Swift#3]

**Comment by ghost** [comment]
我改了里面代码 其实几句注释一些代码稍加修改就OK  但还是希望提供API吧 另外 使用Model传输数据比较好,字典真的不是个好选择,挺好用的一个选择器 望优化

**Comment by WangLiquan** [comment]
谢谢你的认可，这段时间工作重心不在这面了，所以就没有进行相关优化，最近我抽空更新一下吧。
